### ISSUE TITLE
failed to load source for dependency `near-crypto`

### ISSUE THREAD

**Issue by khorolets** [frol/near-cli#1]
Unable to build project

```bash
$ cargo build --release
    Updating git repository `https://github.com/nearprotocol/nearcore`
error: failed to get `near-crypto` as a dependency of package `near-cli v0.1.3 (/Users/khorolets/projects/forks/near-cli)`

Caused by:
  failed to load source for dependency `near-crypto`

Caused by:
  Unable to update https://github.com/nearprotocol/nearcore?rev=312a8f4884f79c1d36f1df0809c6d5f6cc95241d#312a8f48

Caused by:
  object not found - no match for id (312a8f4884f79c1d36f1df0809c6d5f6cc95241d); class=Odb (9); code=NotFound (-3)
```

It's because the commit cannot be found in the nearcore repository anymore.

I'm gonna fix it using some fresh comment. 

However dependencies the project rely on aren't updated often and not suppose to break something. How about to use freshest available nearcore version for them instead?

**Comment by frol** [comment]
It seems that there is something wrong on your side since the commit is definitely there: https://github.com/near/nearcore/commit/312a8f4884f79c1d36f1df0809c6d5f6cc95241d
